apiVersion: v1
kind: ConfigMap
metadata:
  name: pan-mgmt-config
  namespace: kube-system
data:
  PAN_OPERATION_MODE: "daemonset"
  PAN_SERVICE_NAME: "pan-mgmt"
  # Panorama settings
  PAN_PANORAMA_IP: <panorama-IP>
  PAN_PANORAMA_AUTH_KEY: <panorama-auth-key>
  PAN_DEVICE_GROUP: <panorama-device-group>
  PAN_TEMPLATE: <panorama-template-stack>
#Non-mandatory parameters
  #PAN_PANORAMA_CGNAME: ""
  #PAN_CERTIFICATE: ""
  #PAN_CERTKEYFILE: ""
  #PAN_CERTPASSPHRASE: ""
  #PAN_PANORAMA_IP2: ""
  #PAN_GTP_ENABLED: "true"
